name: release
on: [create, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Git repository
      uses: actions/checkout@v4
    - name: Setup Kaitai Struct compiler
      uses: jonahsnider/kaitai-action@v1.0.1
    - run: mkdir -p build
    - name: Run kaitai-struct-compiler
      run: kaitai-struct-compiler --target all --outdir build/ *.ksy
    - name: Zip sources
      run: |
      mkdir -p /tmp/output/
      cd build/
      for d in */; do
          archive="$(basename "$d").zip"
          mv "$d" sf3
          zip -r "/tmp/output/$archive" sf3
          mv sf3 "$d"
      done
    - name: Create release
      continue-on-error: true
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        name: Release ${{ github.ref_name }}
        artifacts: /tmp/output/*.zip
