name: release
on: [create, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Checkout kaitai-struct-compiler
      uses: actions/checkout@v4
      with:
        repository: kaitai-io/kaitai_struct_compiler
        ref: serialization
        path: kaitai-struct-compiler
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: sbt
    - uses: sbt/setup-sbt@v1
    - name: Build the Kaitai Struct Compiler
      shell: bash
      run: |
        cd kaitai-struct-compiler
        sbt --error compilerJVM/stage
        cd ..
    - run: mkdir -p build
    - name: Run kaitai-struct-compiler
      continue-on-error: true
      run: |
        kaitai-struct-compiler/jvm/target/universal/stage/bin/kaitai-struct-compiler              --target all --outdir build/ *.ksy
        kaitai-struct-compiler/jvm/target/universal/stage/bin/kaitai-struct-compiler --read-write --target all --outdir build/ *.ksy
    - name: Zip sources
      run: |
        mkdir -p /tmp/output/
        cd build/
        for d in */; do
            archive="$(basename "$d").zip"
            mv "$d" sf3
            zip -r "/tmp/output/$archive" sf3
            mv sf3 "$d"
        done
    - name: Create release
      continue-on-error: true
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        name: Release ${{ github.ref_name }}
        artifacts: /tmp/output/*.zip
